version: 2
updates:
  # For npm dependencies
  - package-ecosystem: "npm"
    directory: "/src/ui" # Adjust if package.json is in a different directory
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"
  # For Maven dependencies
  - package-ecosystem: "maven"
    directory: "src/health-management" # Adjust if your pom.xml is in a different directory
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
    rebase-strategy: "auto"

