configMapName: mysql-config-map

mysqlpvc:
  storageSize: 1Gi

image:
  registry: ghcr.io/goldjns
  repository: user-database
  tag: v1.11.0-beta
  pullPolicy: "Always"

database:
  containerPort: 3306
database-service:
  clusterIP: None
  servicePort: 3306

configMap:
  server: user-database-service
  name: mysql-config-map
  username: custom
  dburl: jdbc:mysql://user-database-service:3306/rateme_swtp
  dbname: user

  