spring:
    application:
        name: health-management
    datasource:
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        url: jdbc:postgresql://localhost:5432/bitnami_keycloak
        driver-class-name: org.postgresql.Driver
    flyway:
        enabled: true
        baseline-on-migrate: true
    jpa:
        hibernate:
            ddl-auto: update


camunda:
    client:
        mode: self-managed
        auth:  
            client-id: ${ZEEBE_CLIENT_ID}
            client-secret: ${ZEEBE_CLIENT_SECRET}  
            audience: zeebe-api
            issuer: http://localhost:18080/auth/realms/camunda-platform/protocol/openid-connect/token  
        zeebe:
            grpc-address: http://localhost:26500
            rest-address: http://localhost:8080


tasklist:
    client:
        profile: oidc
        enabled: true
        base-url: http://localhost:8082
        auth-url: http://localhost:18080/auth/realms/camunda-platform/protocol/openid-connect/token
        client-id: ${TASKLIST_CLIENT_ID}
        client-secret: ${TASKLIST_CLIENT_SECRET}
        audience: tasklist-api
        defaults:
            load-truncated-variables: true
            return-variables: true
            use-zeebe-user-tasks: true

process:
    health-record:
        create:
            process-id: "createHealthRecord"
        edit:
            process-id: "editHealthRecord"
            

keycloak:
  auth-server-url: http://localhost:18080/auth
  realm: camunda-platform
  resource: health-management
  credentials:
    secret: GZD5tavXxp0XnC0XN8vvGomeWbN8IkLQ
  public-client: false
  confidential-port: 0
  use-resource-role-mappings: true

  
