apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-{{ .Chart.Name}}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: helm-{{ .Chart.Name }}
  template:
    metadata:
      name: helm-{{ .Chart.Name }}
      labels:
        app: helm-{{ .Chart.Name }}
    spec:
      containers:
        - name: helm-{{ .Chart.Name }}
          image: ui:5.0
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          volumeMounts:
            - name: cfg
              mountPath: /usr/share/nginx/html/js/apiConfig.js
              subPath: apiConfig.js
              readOnly: true
      volumes:
        - name: cfg
          configMap:
            name: {{ .Values.configMapName }}
