name: Maven Docker Build

on:
  push:
    branches:
      - main
      - feature/*
      - fix/*
      - chore/*
  workflow_dispatch:

jobs:
  push-docker-images:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_REGISTRY_ACCESS_TOKEN }}

      - name: "Get git tag"
        id: git_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 || echo "latest")
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: "Build Images"
        run: |
          docker build -t health-management:$TAG -f src/health-management/Dockerfile src/health-management
          docker build -t ui:$TAG -f src/ui/Dockerfile src/ui

      - name: "Check Branch Name"
        id: check_branch
        run: |
          if [ "${GITHUB_REF#refs/heads/}" != "main" ]; then
            echo "Branch is not 'main'."
            echo "append_beta=true" >> $GITHUB_ENV
          else
            echo "On the 'main' branch."
            echo "append_beta=false" >> $GITHUB_ENV
          fi

      - name: "Push Images"
        id: push_images
        run: |
          append_beta=${{ steps.check_branch.outputs.append_beta }}
          if [ "$append_beta" == "true" ]; then
            BETA_TAG="${TAG}-beta" 
          else
            BETA_TAG="$TAG"
          fi
          echo "Generated tag: $BETA_TAG"
          BETA_TAG="$BETA_TAG" >> $GITHUB_ENV
          docker tag health-management:$TAG ghcr.io/${{ secrets.PIDUSER }}/health-management:$BETA_TAG
          docker push ghcr.io/${{ secrets.PIDUSER }}/health-management:$BETA_TAG
          docker tag ui:$TAG ghcr.io/${{ secrets.PIDUSER }}/ui:$BETA_TAG
          docker push ghcr.io/${{ secrets.PIDUSER }}/ui:$BETA_TAG