name: Helm deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-dev-job:
    runs-on: ubuntu-latest
    environment: dev
    env:
      NAMESPACE: ${{ vars.NAMESPACE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Deploying to dev environment
        uses: "./.github/template/deploy"
        with:
          environment: dev
          kubeconfig: $ {{secrets.KUBECONFIG}}
          googlecredentials: ${{secrets.GOOGLE_CREDENTIALS}}
          googleproject: ${{ secrets.GKE_PROJECT}}

  deploy-prod-job:
    runs-on: ubuntu-latest
    needs: deploy-dev-job
    environment: prod
    env:
      NAMESPACE: ${{ vars.NAMESPACE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Deploying to prod environment
        uses: "./.github/template/deploy"
        with:
          environment: prod
          kubeconfig: ${{ secrets.KUBECONFIG }}
          googlecredentials: ${{secrets.GOOGLE_CREDENTIALS}}
          googleproject: ${{ secrets. GKE_PROJECT}}